[package]
name = "lucidpane-dependency-evaluation"
version = "0.0.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
windows-animation = "=0.100.0"
windows-core = { version = "=0.100.0", default-features = false }
windows-link = "=0.100.0"

[build-dependencies]
windows-bindgen = "=0.100.0"
