//! Preserve the OLE drag session; insertion geometry is translated by the native hit hook.
#![allow(
    clippy::ref_as_ptr, // Generated by windows::core::implement.
    clippy::inline_always, // Generated by windows::core::implement.
    clippy::wildcard_imports,
    clippy::cast_possible_truncation,
    clippy::cast_sign_loss
)]
use windows::{
    Win32::{
        Foundation::{HWND, POINTL},
        System::{Com::IDataObject, Ole::*, SystemServices::MODIFIERKEYS_FLAGS},
    },
    core::{Interface, Ref, Result, implement},
};
use windows_sys::Win32::{
    Foundation::{POINT, RECT},
    Graphics::Gdi::{ClientToScreen},
    UI::{Controls::*, WindowsAndMessaging::*},
};

#[implement(IDropTarget)]
struct Target {
    view: isize,
    original: IDropTarget,
    over_count: std::cell::Cell<u32>,
    last_point: std::cell::Cell<POINTL>,
}
impl IDropTarget_Impl for Target_Impl {
    fn DragEnter(
        &self,
        data: Ref<IDataObject>,
        keys: MODIFIERKEYS_FLAGS,
        point: &POINTL,
        effect: *mut DROPEFFECT,
    ) -> Result<()> {
        // Preview stays in presentation coordinates. Translating it exposes the
        // hidden native slots in Explorer's insertion indicator.
        self.over_count.set(0);
        self.last_point.set(*point);
        unsafe { self.original.DragEnter(data.as_ref(), keys, *point, effect) }
    }
    fn DragOver(
        &self,
        keys: MODIFIERKEYS_FLAGS,
        point: &POINTL,
        effect: *mut DROPEFFECT,
    ) -> Result<()> {
        self.over_count.set(self.over_count.get().saturating_add(1));
        self.last_point.set(*point);
        unsafe { self.original.DragOver(keys, *point, effect) }
    }
    fn DragLeave(&self) -> Result<()> {
        let result = unsafe { self.original.DragLeave() };
        let last = self.last_point.get();
        append_trace(&format!("DragLeave over_calls={} last={},{} result={result:?}", self.over_count.get(), last.x, last.y));
        result
    }
    fn Drop(
        &self,
        data: Ref<IDataObject>,
        keys: MODIFIERKEYS_FLAGS,
        point: &POINTL,
        effect: *mut DROPEFFECT,
    ) -> Result<()> {
        let before = drop_snapshot(self.view);
        // DragOver already resolved the native insertion identity. Keep its
        // cached target, source state and effect when releasing. A synthetic
        // DragOver in another coordinate space can discard that target entirely.
        let result = unsafe { self.original.Drop(data.as_ref(), keys, *point, effect) };
        // One record per release: no per-frame disk I/O and no file names.
        log_drop(*point, *point, &before, &drop_snapshot(self.view), &result);
        result
    }
}

fn drop_snapshot(view: isize) -> String {
    use std::fmt::Write;
    let hwnd = view as _;
    let mut origin = POINT::default();
    let mut cursor = POINT::default();
    unsafe {
        ClientToScreen(hwnd, &raw mut origin);
        GetCursorPos(&raw mut cursor);
    }
    let count = unsafe { SendMessageW(hwnd, LVM_GETITEMCOUNT, 0, 0) };
    let spacing = unsafe { SendMessageW(hwnd, LVM_GETITEMSPACING, 0, 0) } as u32;
    let mut mark = LVINSERTMARK { cbSize: std::mem::size_of::<LVINSERTMARK>() as u32, ..Default::default() };
    unsafe { SendMessageW(hwnd, LVM_GETINSERTMARK, 0, (&raw mut mark) as isize); }
    let mut marker_bounds = RECT::default();
    unsafe { SendMessageW(hwnd, LVM_GETINSERTMARKRECT, 0, (&raw mut marker_bounds) as isize); }
    let mut record = format!("origin={},{} cursor={},{} spacing={},{} count={count} mark={}:{} mark_rect={},{},{},{} cells=", origin.x, origin.y, cursor.x, cursor.y, spacing & 0xffff, spacing >> 16, mark.iItem, mark.dwFlags, marker_bounds.left, marker_bounds.top, marker_bounds.right, marker_bounds.bottom);
    if (1..=crate::protocol::MAX_LAYOUT_ITEMS as isize).contains(&count) {
        for item in 0..count {
            let mut p = POINT::default();
            super::bypass(|| unsafe {
                SendMessageW(hwnd, LVM_GETITEMPOSITION, item as usize, (&raw mut p) as isize)
            });
            let hidden = super::hidden::is_hidden(item as i32);
            let _ = write!(record, " {item}:({},{}){}", p.x, p.y, if hidden { "H" } else { "" });
        }
    }
    record
}

fn log_drop(point: POINTL, mapped: POINTL, before: &str, after: &str, result: &Result<()>) {
    append_trace(&format!("Drop input={},{} mapped={},{} result={result:?}\nbefore {before}\nafter  {after}", point.x, point.y, mapped.x, mapped.y));
}

fn append_trace(record: &str) {
    use std::io::Write;
    let Some(local) = std::env::var_os("LOCALAPPDATA") else { return; };
    let path = std::path::PathBuf::from(local).join("LucidPane").join("hook-drop.log");
    if let Ok(mut file) = std::fs::OpenOptions::new().create(true).append(true).open(path) {
        let _ = writeln!(file, "{:?} {record}", std::time::SystemTime::now());
    }
}

pub(super) struct Registration {
    view: HWND,
    original: IDropTarget,
    proxy: IDropTarget,
}
impl Registration {
    pub(super) unsafe fn attach(
        view: windows_sys::Win32::Foundation::HWND,
    ) -> std::result::Result<Option<Self>, String> {
        // OleDropTargetInterface is an implementation-specific discovery point. Only
        // same-process, same-thread views already validated by GeometrySession reach here.
        let mut owner = view;
        let pointer = loop {
            if owner.is_null() { return Ok(None); }
            let thread = unsafe { GetWindowThreadProcessId(owner, std::ptr::null_mut()) };
            if thread != unsafe { windows_sys::Win32::System::Threading::GetCurrentThreadId() } { return Ok(None); }
            let pointer = unsafe { GetPropW(owner, windows_sys::w!("OleDropTargetInterface")) };
            if !pointer.is_null() { break pointer; }
            owner = unsafe { GetParent(owner) };
        };
        let borrowed = unsafe { IDropTarget::from_raw_borrowed(&pointer) }
            .ok_or("Desktop drop target unavailable")?;
        let original: IDropTarget = borrowed.cast().map_err(|e| e.to_string())?;
        let proxy: IDropTarget = Target {
            view: view as isize,
            original: original.clone(),
            over_count: std::cell::Cell::new(0),
            last_point: std::cell::Cell::new(POINTL::default()),
        }
        .into();
        let hwnd = HWND(owner);
        unsafe { RevokeDragDrop(hwnd) }.map_err(|e| e.to_string())?;
        if let Err(error) = unsafe { RegisterDragDrop(hwnd, &proxy) } {
            let _ = unsafe { RegisterDragDrop(hwnd, &original) };
            return Err(error.to_string());
        }
        Ok(Some(Self {
            view: hwnd,
            original,
            proxy,
        }))
    }
}
impl Drop for Registration {
    fn drop(&mut self) {
        unsafe {
            let current = GetPropW(self.view.0, windows_sys::w!("OleDropTargetInterface"));
            if current == self.proxy.as_raw() {
                let _ = RevokeDragDrop(self.view);
                let _ = RegisterDragDrop(self.view, &self.original);
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    type Events = std::rc::Rc<std::cell::RefCell<Vec<(&'static str, i32, i32)>>>;
    #[implement(IDropTarget)]
    struct TestTarget { events: Events }
    impl IDropTarget_Impl for TestTarget_Impl {
        fn DragEnter(
            &self,
            _: Ref<IDataObject>,
            _: MODIFIERKEYS_FLAGS,
            point: &POINTL,
            effect: *mut DROPEFFECT,
        ) -> Result<()> {
            self.events.borrow_mut().push(("enter",point.x,point.y));
            unsafe {
                *effect = DROPEFFECT_COPY;
            }
            Ok(())
        }
        fn DragOver(
            &self,
            _: MODIFIERKEYS_FLAGS,
            point: &POINTL,
            effect: *mut DROPEFFECT,
        ) -> Result<()> {
            self.events.borrow_mut().push(("over",point.x,point.y));
            unsafe {
                *effect = DROPEFFECT_COPY;
            }
            Ok(())
        }
        fn DragLeave(&self) -> Result<()> {
            Ok(())
        }
        fn Drop(
            &self,
            _: Ref<IDataObject>,
            _: MODIFIERKEYS_FLAGS,
            point: &POINTL,
            effect: *mut DROPEFFECT,
        ) -> Result<()> {
            self.events.borrow_mut().push(("drop",point.x,point.y));
            unsafe {
                *effect = DROPEFFECT_COPY;
            }
            Ok(())
        }
    }
    #[test]
    fn ole_proxy_forwards_and_restores_original_registration() {
        unsafe {
            OleInitialize(None).unwrap();
            let view = CreateWindowExW(
                0,
                windows_sys::w!("STATIC"),
                windows_sys::w!("Drop proxy test"),
                WS_POPUP,
                0,
                0,
                100,
                100,
                std::ptr::null_mut(),
                std::ptr::null_mut(),
                std::ptr::null_mut(),
                std::ptr::null(),
            );
            assert!(!view.is_null());
            let events: Events = std::rc::Rc::default();
            let original: IDropTarget = TestTarget { events: events.clone() }.into();
            RegisterDragDrop(HWND(view), &original).unwrap();
            let registration = Registration::attach(view)
                .unwrap()
                .expect("OLE property must be discoverable");
            let mut effect = DROPEFFECT_NONE;
            registration
                .proxy
                .DragOver(
                    MODIFIERKEYS_FLAGS(0),
                    POINTL { x: 10, y: 10 },
                    &raw mut effect,
                )
                .unwrap();
            assert_eq!(effect, DROPEFFECT_COPY);
            registration.proxy.Drop(None::<&IDataObject>, MODIFIERKEYS_FLAGS(0),
                POINTL { x:637,y:1336 }, &raw mut effect).unwrap();
            assert_eq!(&*events.borrow(), &[("over",10,10),("drop",637,1336)],
                "Drop must preserve the point and must not synthesize a second DragOver");
            drop(registration);
            assert_eq!(
                GetPropW(view, windows_sys::w!("OleDropTargetInterface")),
                original.as_raw()
            );
            RevokeDragDrop(HWND(view)).unwrap();
            DestroyWindow(view);
            drop(original);
            OleUninitialize();
        }
    }
}
