"""Generate an explicit, reviewable profile from previously verified public symbols."""
import json
from pathlib import Path

metadata = json.loads(Path('target/symbols/comctl32.dll.filtered.symbols.json').read_text())
data = Path(metadata['image']).read_bytes()
keys = ['CLVIconView::GetRectsOwnerData(', 'CLVIconView::v_ItemHitTest(', 'CLVView::OnGetItemPosition(', 'CLVInsertionMarkManager::OnGetInsertMarkRect(', 'CLVView::v_OnInsertMarkHitTest(']
# The position symbol was extracted in the original, separately verified symbol inventory.
position = json.loads(Path('target/symbols/comctl32.dll.symbols.json').read_text())
assert metadata['guid'] == position['guid'] and metadata['pdb_dbi_age'] == position['pdb_dbi_age']
symbols = metadata['symbols'] + position['symbols']
selected = []
for key in keys:
    matches = {s['rva']: s for s in symbols if key in s['name']}
    assert len(matches) == 1, (key, matches)
    selected.append(next(iter(matches.values())))
hash_value = 0xcbf29ce484222325
for value in data:
    hash_value = ((hash_value ^ value) * 0x100000001b3) & 0xffffffffffffffff
lines = [
    '// Generated by tools/generate_geometry_profile.py; not a portable Windows ABI.',
    '// PDB GUID ' + metadata['guid'] + ', DBI age ' + str(metadata['pdb_dbi_age']),
    'pub const IMAGE_HASH: u64 = 0x' + '_'.join(format(hash_value, '016x')[i:i+4] for i in range(0,16,4)) + ';',
    'pub const IMAGE_SIZE: usize = ' + format(len(data),'_') + ';',
    'pub const TARGETS: [(usize, [u8; 24]); 5] = [',
]
for symbol in selected:
    rva = symbol['rva']
    raw = next(offset+rva-start for start,size,offset in metadata['sections'] if start <= rva < start+size)
    lines.append('    // ' + symbol['name'])
    lines.append('    (0x%x, [%s]),' % (rva, ', '.join('0x%02x' % b for b in data[raw:raw+24])))
lines.append('];')
Path('crates/luciddesk-explorer/src/geometry/profile.rs').write_text('\n'.join(lines)+'\n', encoding='utf-8')
print('Generated exact-image geometry profile:', hex(hash_value), [hex(s['rva']) for s in selected])
